name: Build Windows executable

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pyinstaller

      - name: Build executable
        shell: pwsh
        run: |
          pyinstaller --onefile --name mcp-sandtimer src/mcp_sandtimer/__main__.py
          $version = "${{ github.ref_name }}"
          $output = "dist\\mcp-sandtimer.exe"
          if (Test-Path $output) {
            Rename-Item -Path $output -NewName "mcp-sandtimer-$version.exe"
          }

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/mcp-sandtimer-${{ github.ref_name }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
